# Generated by Django 3.1.7 on 2021-06-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210622_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprovider',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='item_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.itemprovider'),
        ),
    ]
