# Generated by Django 3.1.7 on 2021-06-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210622_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='item_provider',
        ),
        migrations.AddField(
            model_name='itemprovider',
            name='provider',
            field=models.ManyToManyField(blank=True, null=True, related_name='items_providers', to='api.Provider'),
        ),
    ]
