# Generated by Django 3.1.7 on 2021-06-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210623_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributioncenter',
            old_name='description',
            new_name='warehouse',
        ),
    ]
