# Generated by Django 3.1.7 on 2021-06-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210623_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatedcompany',
            name='client_key',
        ),
    ]
