# Generated by Django 3.1.7 on 2021-06-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_associatedcompany_client_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
