# Generated by Django 3.1.7 on 2021-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210624_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('normal', 'Normal'), ('plate', 'Plate'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='normal', max_length=10),
        ),
    ]
